In [1]:
import numpy as np

In [2]:
def softmax(vec):
  denumerator = np.exp(vec - np.max(vec, axis=-1, keepdims=True))  # 큰 숫자에 대한 overflow를 막기 위해 추가한 부분
  numerator = np.sum(denumerator, axis=-1, keepdims=True)
  return denumerator / numerator

vec = np.array([[1, 2, 0], [-1, 0, 1], [-10, 0, 10]])
softmax(vec)

array([[2.44728471e-01, 6.65240956e-01, 9.00305732e-02],
       [9.00305732e-02, 2.44728471e-01, 6.65240956e-01],
       [2.06106005e-09, 4.53978686e-05, 9.99954600e-01]])

## Step By Step

In [3]:
vec = np.array([[1, 2, 0], [-1, 0, 1], [-10, 0, 10]])
vec

array([[  1,   2,   0],
       [ -1,   0,   1],
       [-10,   0,  10]])

In [4]:
np.max(vec, axis=-1, keepdims=True)

array([[ 2],
       [ 1],
       [10]])

In [5]:
vec - np.max(vec, axis=-1, keepdims=True)

array([[ -1,   0,  -2],
       [ -2,  -1,   0],
       [-20, -10,   0]])

In [6]:
denumerator = np.exp(vec - np.max(vec, axis=-1, keepdims=True))
denumerator

array([[3.67879441e-01, 1.00000000e+00, 1.35335283e-01],
       [1.35335283e-01, 3.67879441e-01, 1.00000000e+00],
       [2.06115362e-09, 4.53999298e-05, 1.00000000e+00]])

In [7]:
 numerator = np.sum(denumerator, axis=-1, keepdims=True)
 numerator

array([[1.50321472],
       [1.50321472],
       [1.0000454 ]])

In [8]:
denumerator / numerator

array([[2.44728471e-01, 6.65240956e-01, 9.00305732e-02],
       [9.00305732e-02, 2.44728471e-01, 6.65240956e-01],
       [2.06106005e-09, 4.53978686e-05, 9.99954600e-01]])