In [1]:
import numpy as np

test_array = np.array(["1", "4", 5, 8], float)

print(test_array)
print(type(test_array))
print(type(test_array[3]))

[1. 4. 5. 8.]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [2]:
test_array = np.array([[[1, "8"],[1, "8"],[1, "8"]],
                       [[1, "8"],[1, "8"],[1, "8"]],
                       [[1, "8"],[1, "8"],[1, "8"]],
                       [[1, "8"],[1, "8"],[1, "8"]]], np.float32)

print(test_array.dtype)  # ndarray 전체의 데이터 Type을 반환
print(test_array.shape)  # ndarray shape을 반환 
print(test_array.ndim)   # number of dimension
print(test_array.size)   # number of data

float32
(4, 3, 2)
3
24


In [3]:
test_matrix = [[1,2,3,4], [5,6,7,8]]

print(np.array(test_matrix).shape)
print(np.array(test_matrix).reshape(2,2,2))
print(np.array(test_matrix).reshape(8,).shape)
print(np.array(test_matrix).reshape(-1,2).shape)  # -1 : size를 기반으로 row 개수 선정

(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(8,)
(4, 2)


In [4]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], int)

print(a)
print(a[0, 0])  # Two dimensional array representation
print(a[0][0])

[[1 2 3]
 [4 5 6]]
1
1


In [5]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)

print(a[:, 2:])   # 전체 row의 2열 이상
print(a[1, 1:3])  # 1 row의 1~2열
print(a[1:2])     # 1 row 전체

[[ 3  4  5]
 [ 8  9 10]]
[7 8]
[[ 6  7  8  9 10]]


In [6]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)

print(a[:, ::2])    # 전체 row의 2간격 column
print(a[::2, ::3])  # 홀수 row의 3간격 column

[[ 1  3  5]
 [ 6  8 10]]
[[1 4]]


In [7]:
np.arange(0, 5, 0.5).reshape(-1, 5)

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5]])

In [8]:
z = np.zeros(shape=(10,), dtype=np.int8)
o = np.ones(shape=(2,5), dtype=np.int8)
e = np.empty(shape=(10,), dtype=np.int8)  # shape만 주어지고 비어있는 ndarray 생성 (memory initialization 안됨)

print(z)
print(o)
print(e)

[0 0 0 0 0 0 0 0 0 0]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[ 32 111  57   2   0   0   0   0   0   0]


In [9]:
i = np.eye(3)
n = np.eye(N=3, M=5, dtype=np.int8)
k = np.eye(N=3, M=5, k=2, dtype=np.int8)  # k = start index

print(i)
print(n)
print(k)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]
[[0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [10]:
u = np.random.uniform(0, 1, 10).reshape(2, 5)  # 균등 분포
n = np.random.normal(0, 1, 10).reshape(2, 5)   # 정규 분포

print(u)
print(n)

[[0.79911654 0.39591222 0.69292923 0.02523411 0.55770022]
 [0.12698392 0.73762727 0.26166284 0.95596341 0.92487293]]
[[-0.55062125 -0.7146251  -0.60507011  0.08581904 -0.90748115]
 [-0.1132815   0.4065792  -1.70684328 -0.50434708  0.67549178]]


In [11]:
test_array = np.arange(1, 13).reshape(3, 4)

r_sum = test_array.sum(axis=1)  # 가로(row) 방향
c_sum = test_array.sum(axis=0)  # 세로(column) 방향

print(test_array)
print(r_sum)
print(c_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[15 18 21 24]


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))

d = np.array([[1], [2], [3]])
e = np.array([[4], [5], [6]])
f = np.hstack((d, e))

print(c)
print(f)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [13]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
c = np.concatenate((a, b), axis=0)

d = np.array([[1, 2], [3, 4]])
e = np.array([[5, 6]])
f = np.concatenate((d, e.T), axis=1)

print(c)
print(f)

[[1 2 3]
 [4 5 6]]
[[1 2 5]
 [3 4 6]]


In [14]:
matrix_a = np.arange(1, 13).reshape(3, 4)
matrix_b = matrix_a * matrix_a

print(matrix_a)
print(matrix_b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [15]:
test_a =  np.arange(1, 7).reshape(2, 3)
test_b =  np.arange(7, 13).reshape(3, 2)

test_c = test_a.dot(test_b)

print(test_a)
print(test_b)
print(test_c)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


In [16]:
test_matrix = np.array([[1, 2, 3], [4, 5, 6]], float)
scalar = 3

r = test_matrix + scalar

print(test_matrix)
print(scalar)
print(r)

[[1. 2. 3.]
 [4. 5. 6.]]
3
[[4. 5. 6.]
 [7. 8. 9.]]


In [17]:
matrix_a = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]], float)
matrix_b = np.array([[1, 2, 3]], float)

matrix_c = matrix_a + matrix_b

print(matrix_a)
print(matrix_b)
print(matrix_c)

[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
[[1. 2. 3.]]
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [18]:
a = np.arange(10)

print(a)
print(a>5)          # 각 element와 비교한 결과를 array로 반환
print(np,any(a>5))  # element 중 하나라도 만족하면 True
print(np,any(a<0))  # element 중 하나도 만족하지 못하면 False
print(np,all(a>5))  # element 모두 만족하지 못하면 False
print(np,all(a<10)) # element 모두 만족하면 True

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'> True
<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'> False
<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'> False
<module 'numpy' from '/usr/local/lib/python3.8/dist-packages/numpy/__init__.py'> True


In [19]:
a = np.arange(5) * 10
b = np.where(a < 30, 1, 0)
c = np.where(a > 20)

print(a)
print(b)
print(c)

[ 0 10 20 30 40]
[1 1 1 0 0]
(array([3, 4]),)


In [20]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])

b = np.argmin(a)  # index 값으로 반환
c = np.argmax(a)  # index 값으로 반환

print(a)
print(b)
print(c)

[ 1  2  4  5  8 78 23  3]
0
5


In [21]:
a = np.array([[1, 10, 4, 7], [8, 5, 78, 23], [9, 7, 6, 3]])

b = np.argmin(a, axis=0)  # column 방향
c = np.argmax(a, axis=1)  # row 방향

print(a)
print(b)
print(c)

[[ 1 10  4  7]
 [ 8  5 78 23]
 [ 9  7  6  3]]
[0 1 0 2]
[1 2 0]


In [22]:
a = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
b = a[a > 5]

c = a < 3
d = a[c]

print(a)
print(b)
print(c)
print(d)

[1. 4. 0. 2. 3. 8. 9. 7.]
[8. 9. 7.]
[ True False  True  True False False False False]
[1. 0. 2.]


In [23]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)  # 반드시 integer로 선언

c = a[b]       # bracket index
d = a.take(b)  # bracket index와 같은 효과

print(a)
print(b)
print(c)
print(d)

[2. 4. 6. 8.]
[0 0 1 3 2 1]
[2. 2. 4. 8. 6. 4.]
[2. 2. 4. 8. 6. 4.]
