In [2]:
import numpy as np

X = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

print(X)

[[ 1 -2  3]
 [ 7  5  0]
 [-2 -1  2]]


In [5]:
X = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

Y = np.array([[0, 1],
              [1, -1],
              [-2, 1]])

Z = X @ Y

print(Z)

[[-8  6]
 [ 5  2]
 [-5  1]]


In [6]:
X = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

Y = np.array([[0, 1, -1],
              [1, -1, 0]])

Z = np.inner(X, Y)

print(Z)

[[-5  3]
 [ 5  2]
 [-3 -1]]


In [8]:
X = np.array([[1, -2, 3],
              [7, 5, 0],
              [-2, -1, 2]])

X_inv = np.linalg.inv(X)

Z = X @ X_inv

print(X_inv)
print(Z)

[[ 0.21276596  0.0212766  -0.31914894]
 [-0.29787234  0.17021277  0.44680851]
 [ 0.06382979  0.10638298  0.40425532]]
[[ 1.00000000e+00 -1.38777878e-17  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00 -5.55111512e-17]
 [-2.77555756e-17  0.00000000e+00  1.00000000e+00]]


In [10]:
Y = np.array([[0, 1],
              [1, -1],
              [-2, 1]])

Y_pinv = np.linalg.pinv(Y)  # 행과 열의 개수가 다르기에 역행렬을 못구하는 경우지만, 유사 역행렬 계산

Z = Y_pinv @ Y

print(Y_pinv)
print(Z)

[[ 5.00000000e-01  4.09730229e-17 -5.00000000e-01]
 [ 8.33333333e-01 -3.33333333e-01 -1.66666667e-01]]
[[ 1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00]]


In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, y)

y_test = model.predict(x_test)


# Moore-Penrose 역행렬

beta = np.linalg.pinv(X) @ y
y_test = np.append(x_test) @ beta

# 위와 같이만 해서는 다른 결과가 나옴

# y절편 항을 직접 추가해줘야 같은 결과

X_ = np.array([np.append(x, [1]) for x in X])  # intercept(y절편) 항 추가
beta = np.linalg.pinv(X_) @ y
y_test = np.append(x_test, [1]) @ beta