In [1]:
import numpy as np

## 1D Array with NumPy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print(f'Rank  of t: {t.ndim}')
print(f'Shape of t: {t.shape}')

Rank  of t: 1
Shape of t: (7,)


In [4]:
print(f't[0], t[1], t[-1] = {t[0]}, {t[1]}, {t[-1]}')  # Element
print(f't[2:5], t[4:-1]   = {t[2:5]}, {t[4:-1]}')      # Slicing
print(f't[:2], t[3:]      = {t[:2]}, {t[3:]}')         # Slicing

t[0], t[1], t[-1] = 0.0, 1.0, 6.0
t[2:5], t[4:-1]   = [2. 3. 4.], [4. 5.]
t[:2], t[3:]      = [0. 1.], [3. 4. 5. 6.]


## 2D Array with NumPy

In [5]:
t = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.],
              [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print(f'Rank  of t: {t.ndim}')
print(f'Shape of t: {t.shape}')

Rank  of t: 2
Shape of t: (4, 3)


## 1D Array with PyTorch

In [7]:
import torch

In [8]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [9]:
print(f'Rank  of t: {t.dim()}')
print(f'Shape of t: {t.shape}')
print(f'Size  of t: {t.size()}')

Rank  of t: 1
Shape of t: torch.Size([7])
Size  of t: torch.Size([7])


In [10]:
print(f't[0], t[1], t[-1] = {t[0]}, {t[1]}, {t[-1]}')  # Element
print(f't[2:5], t[4:-1]   = {t[2:5]}, {t[4:-1]}')      # Slicing
print(f't[:2], t[3:]      = {t[:2]}, {t[3:]}')         # Slicing

t[0], t[1], t[-1] = 0.0, 1.0, 6.0
t[2:5], t[4:-1]   = tensor([2., 3., 4.]), tensor([4., 5.])
t[:2], t[3:]      = tensor([0., 1.]), tensor([3., 4., 5., 6.])


## 2D Array with PyTorch

In [11]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [12]:
print(f'Rank  of t: {t.dim()}')
print(f'Shape of t: {t.size()}')

Rank  of t: 2
Shape of t: torch.Size([4, 3])


In [13]:
print(f't[:, 1]        = {t[:, 1]}')
print(f't[:, 1].size() = {t[:, 1].size()}')
print(f't[:, :-1]      = {t[:, :-1]}')

t[:, 1]        = tensor([ 2.,  5.,  8., 11.])
t[:, 1].size() = torch.Size([4])
t[:, :-1]      = tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


## Broadcasting

In [14]:
# Same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1 + m2)

tensor([[5., 5.]])


In [15]:
# ventor + scalar
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3]])  # 3 → [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [16]:
# 2x1 vector + 1x2 vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


## Multiplication vs Matrix Multiplication

In [17]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(f'Shaoe of Matrix 1: {m1.shape}')
print(f'Shaoe of Matrix 2: {m2.shape}')
print(m1.matmul(m2))
print()
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(f'Shaoe of Matrix 1: {m1.shape}')
print(f'Shaoe of Matrix 2: {m2.shape}')
print(m1 * m2)
print(m1.mul(m2))


-------------
Mul vs Matmul
-------------
Shaoe of Matrix 1: torch.Size([2, 2])
Shaoe of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])

Shaoe of Matrix 1: torch.Size([2, 2])
Shaoe of Matrix 2: torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## Mean

In [18]:
t = torch.FloatTensor([[1, 2]])
print(t.mean())

tensor(1.5000)


In [19]:
t = torch.LongTensor([[1, 2]])  # Integer → can't use mean()
try:
  print(t.mean())
except Exception as exc:
  print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


In [20]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


## Sum

In [22]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [23]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


## Max and Argmax

In [24]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [25]:
print(t.max())

tensor(4.)


In [26]:
print(t.max(dim=0))  # second value is the argmax: the index of the element with maximum value

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [27]:
print(f'Max   : {t.max(dim=0)[0]}')
print(f'Argmax: {t.max(dim=0)[1]}')

Max   : tensor([3., 4.])
Argmax: tensor([1, 1])


In [28]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


## View (Reshape)

In [29]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [30]:
print(ft.view([-1, 3]))
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [31]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

In [32]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [33]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze

In [34]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [35]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [36]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [37]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [38]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [39]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [40]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [41]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [42]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenation

In [43]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [44]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking

In [45]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [46]:
print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [47]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros Like

In [48]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [49]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation

In [50]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [51]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))  # 변수에 바로 적용
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
